name: LavaProof
version: ${project.version}
main: me.marcify.lavaProof.LavaProof
api-version: '1.21'

commands:
  lavaproof:
    description: LavaProof command
    usage: /lavaproof

permissions:
  lavaproof.admin:
    description: Permission to use all LavaProof commands
    default: op
    children:
        lavaproof.reload: true
        lavaproof.add: true
        lavaproof.remove: true
  lavaproof.reload:
    description: Reload the config.yml file
    default: op
  lavaproof.add:
    description: Add an item to the no-burn-items and no-explosion-items list
    default: op
  lavaproof.add.lava:
    description: Add an item to the no-burn-items list
    default: false
  lavaproof.add.explosion:
    description: Add an item to the no-explosion-items list
    default: false
  lavaproof.remove:
    description: Remove an item from the no-burn-items list
    default: op
  lavaproof.remove.lava:
    description: Remove an item from the no-burn-items list
    default: false
  lavaproof.remove.explosion:
    description: Remove an item from the no-explosion-items list
    default: false

